export { Hero } from './hero'
export { About } from './about'
export { Work } from './work'
export { Education } from './education'
export { Skills } from './skills'
export { Technology } from './technology'
export { Projects } from './projects'
export { Contact } from './contact'
